package com.example.waterbalancemonitor.presentation.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF0061A4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF00696B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCEE7E8)
val LightOnSecondaryContainer = Color(0xFF002021)
val LightTertiary = Color(0xFF006874)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF97F0FF)
val LightOnTertiaryContainer = Color(0xFF001F24)
val LightBackground = Color(0xFFFCFCFF)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFCFCFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFDEE3EB)
val LightOnSurfaceVariant = Color(0xFF42474E)
val LightOutline = Color(0xFF72777F)

val DarkPrimary = Color(0xFFA5D8FF)
val DarkOnPrimary = Color(0xFF003258)
val DarkPrimaryContainer = Color(0xFF00497D)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFF9EE6E0)
val DarkOnSecondary = Color(0xFF003738)
val DarkSecondaryContainer = Color(0xFF004F50)
val DarkOnSecondaryContainer = Color(0xFFCEE7E8)
val DarkTertiary = Color(0xFFB2EBF2)
val DarkOnTertiary = Color(0xFF00363D)
val DarkTertiaryContainer = Color(0xFF004F58)
val DarkOnTertiaryContainer = Color(0xFF97F0FF)
val DarkBackground = Color(0xFF1A1C1E)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF1A1C1E)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF42474E)
val DarkOnSurfaceVariant = Color(0xFFC2C7CF)
val DarkOutline = Color(0xFF8C9199)
